### ISSUE TITLE
I had some problem with converter_pdf.py parsing issue

### ISSUE THREAD

**Issue by okaragoz** [vinaykanigicherla/pdftolatex#1]
Hello  @vinaykanigicherla,

I am experiencing the trouble you indicated in your statement, and this little tool can be really useful. But when I tried to run it myself, I encountered a problem like this.

`python3 convert_pdf.py --filepath ./98JE00360.pdf                                                      
usage: convert_pdf.py [-h] [--folderpath FOLDERPATH] filepath
convert_pdf.py: error: unrecognized arguments: --filepath`

Thanks,
Oz.

**Comment by vinaykanigicherla** [comment]
Thanks for catching this issue! This was due to a small typo in the argparse code. Should be fixed now. Feel free to reopen the issue if there are still issues.
